version: "3.9"
services:
  redis:
    image: redis:alpine
    command: redis-server --maxmemory-policy noeviction
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
